name: Build Aseprite for Intel macOS

on: [push]

jobs:
  build:
    runs-on: macos-12
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.13
    steps:
      - uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          xcode-select --install || true
          brew install cmake ninja

      - name: 获取 Skia 库 (x86_64)
        run: |
          wget https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-macOS-Release-x64.zip
          unzip Skia-macOS-Release-x64.zip -d $HOME/deps/skia

      - name: 配置 CMake
        run: |
          git clone --recursive https://github.com/aseprite/aseprite.git
          cd aseprite
          mkdir build && cd build
          cmake \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_OSX_ARCHITECTURES=x86_64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=$HOME/deps/skia \
            -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64 \
            -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-x64/libskia.a \
            -G Ninja ..

      - name: 编译
        run: |
          cd aseprite/build
          ninja aseprite

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: Aseprite-Intel-MacOS
          path: aseprite/build/bin/aseprite
